echo:
  picklist:
  - ../../lab/05.0/echo/picklist/01-picklist.csv
  protocol:
  - ../../lab/05.0/echo/2022-04-23-exp02.epr
  surveys:
  - ../../lab/05.0/echo/2022-04-25/E5XX-1564_Survey_Source[4](UnknownBarCode).csv
  - ../../lab/05.0/echo/2022-04-25/E5XX-1564_Survey_Source[3](UnknownBarCode).csv
  - ../../lab/05.0/echo/2022-04-25/E5XX-1564_Survey_Source[2](UnknownBarCode).csv
  transfers:
  - ../../lab/05.0/echo/2022-04-25/E5XX-1564_Transfer_1650874342_Exceptions.csv
  - ../../lab/05.0/echo/2022-04-25/E5XX-1564_Transfer_1650874342.csv
nb:
- ../../lab/05.0/nb/lab.ipynb
platereader:
  plate_1:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,131152_220425103858.CSV
      test_run_no: '2870'
      time: '13:11:56'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,0917031yqp0917.CSV
      test_run_no: '2990'
      time: 09:17:03
      user: USER
  plate_10:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,143647.CSV
      test_run_no: '2879'
      time: '14:36:47'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1054301yqp1054.CSV
      test_run_no: '2999'
      time: '10:54:30'
      user: USER
  plate_11:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,144613.CSV
      test_run_no: '2880'
      time: '14:46:13'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1104481yqp1104.CSV
      test_run_no: '3000'
      time: '11:04:48'
      user: USER
  plate_12:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,145554.CSV
      test_run_no: '2881'
      time: '14:55:54'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1115101yqp1115.CSV
      test_run_no: '3001'
      time: '11:15:10'
      user: USER
  plate_13:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,150536.CSV
      test_run_no: '2882'
      time: '15:05:36'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1125301yqp1125.CSV
      test_run_no: '3002'
      time: '11:25:30'
      user: USER
  plate_14:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,151520.CSV
      test_run_no: '2883'
      time: '15:15:20'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1135431yqp1135.CSV
      test_run_no: '3003'
      time: '11:35:43'
      user: USER
  plate_15:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,152501.CSV
      test_run_no: '2884'
      time: '15:25:01'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1146461yqp1146.CSV
      test_run_no: '3004'
      time: '11:46:46'
      user: USER
  plate_2:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,132125.CSV
      test_run_no: '2871'
      time: '13:21:25'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,0929011yqp0929.CSV
      test_run_no: '2991'
      time: 09:29:01
      user: USER
  plate_3:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,133051.CSV
      test_run_no: '2872'
      time: '13:30:51'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,0940011yqp0940.CSV
      test_run_no: '2992'
      time: 09:40:01
      user: USER
  plate_4:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,134015.CSV
      test_run_no: '2873'
      time: '13:40:15'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,0951061yqp0951.CSV
      test_run_no: '2993'
      time: 09:51:06
      user: USER
  plate_5:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,134939.CSV
      test_run_no: '2874'
      time: '13:49:39'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1002271yqp1002.CSV
      test_run_no: '2994'
      time: '10:02:27'
      user: USER
  plate_6:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,135905.CSV
      test_run_no: '2875'
      time: '13:59:05'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1012221yqp1012.CSV
      test_run_no: '2995'
      time: '10:12:22'
      user: USER
  plate_7:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,140831.CSV
      test_run_no: '2876'
      time: '14:08:31'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1022181yqp1022.CSV
      test_run_no: '2996'
      time: '10:22:18'
      user: USER
  plate_8:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,141757.CSV
      test_run_no: '2877'
      time: '14:17:57'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1032071yqp1032.CSV
      test_run_no: '2997'
      time: '10:32:07'
      user: USER
  plate_9:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,142723.CSV
      test_run_no: '2878'
      time: '14:27:23'
      user: USER
    test:
      date: 27/04/2022
      id1: null
      id2: 1yqp
      machine: BMG CLARIOstar
      path: ../../lab/05.0/platereader/27042022,1043251yqp1043.CSV
      test_run_no: '2998'
      time: '10:43:25'
      user: USER
uv-vis:
  post-dilution spec:
  - ../../lab/05.0/uv-vis/20220427-05-1yqp-post-dil.csv
  pre-dilution spec:
  - ../../lab/05.0/uv-vis/20220427-05-1yqp-predil.csv

