protein:
        BM3 Heme 1YQP
echo:
  picklist:
  - ../../lab/04.0/echo/picklist/01-picklist.csv
  protocol:
  - ../../lab/04.0/echo/2022-04-23-exp02.epr
  surveys:
  - ../../lab/04.0/echo/2022-04-24/E5XX-1564_Survey_Source[4](UnknownBarCode).csv
  - ../../lab/04.0/echo/2022-04-24/E5XX-1564_Survey_Source[3](UnknownBarCode).csv
  - ../../lab/04.0/echo/2022-04-24/E5XX-1564_Survey_Source[2](UnknownBarCode).csv
  transfers:
  - ../../lab/04.0/echo/2022-04-24/E5XX-1564_Transfer_1650797192.csv
  - ../../lab/04.0/echo/2022-04-24/E5XX-1564_Transfer_1650797192_Exceptions.csv
nb:
- ../../lab/04.0/nb/lab.ipynb
platereader:
  plate_1:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,131152_220425103858.CSV
      test_run_no: '2870'
      time: '13:11:56'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2975.CSV
      test_run_no: '2975'
      time: '15:45:42'
      user: USER
  plate_10:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,143647.CSV
      test_run_no: '2879'
      time: '14:36:47'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2984.CSV
      test_run_no: '2984'
      time: '17:11:49'
      user: USER
  plate_11:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,144613.CSV
      test_run_no: '2880'
      time: '14:46:13'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2985.CSV
      test_run_no: '2985'
      time: '17:21:18'
      user: USER
  plate_12:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,145554.CSV
      test_run_no: '2881'
      time: '14:55:54'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2986.CSV
      test_run_no: '2986'
      time: '17:31:09'
      user: USER
  plate_13:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,150536.CSV
      test_run_no: '2882'
      time: '15:05:36'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2987.CSV
      test_run_no: '2987'
      time: '17:40:52'
      user: USER
  plate_14:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,151520.CSV
      test_run_no: '2883'
      time: '15:15:20'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2988.CSV
      test_run_no: '2988'
      time: '17:50:42'
      user: USER
  plate_15:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,152501.CSV
      test_run_no: '2884'
      time: '15:25:01'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2989.CSV
      test_run_no: '2989'
      time: '18:00:29'
      user: USER
  plate_2:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,132125.CSV
      test_run_no: '2871'
      time: '13:21:25'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2976.CSV
      test_run_no: '2976'
      time: '15:55:37'
      user: USER
  plate_3:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,133051.CSV
      test_run_no: '2872'
      time: '13:30:51'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2977.CSV
      test_run_no: '2977'
      time: '16:05:09'
      user: USER
  plate_4:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,134015.CSV
      test_run_no: '2873'
      time: '13:40:15'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2978.CSV
      test_run_no: '2978'
      time: '16:14:39'
      user: USER
  plate_5:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,134939.CSV
      test_run_no: '2874'
      time: '13:49:39'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2979.CSV
      test_run_no: '2979'
      time: '16:24:11'
      user: USER
  plate_6:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,135905.CSV
      test_run_no: '2875'
      time: '13:59:05'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2980.CSV
      test_run_no: '2980'
      time: '16:33:44'
      user: USER
  plate_7:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,140831.CSV
      test_run_no: '2876'
      time: '14:08:31'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2981.CSV
      test_run_no: '2981'
      time: '16:43:15'
      user: USER
  plate_8:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,141757.CSV
      test_run_no: '2877'
      time: '14:17:57'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2982.CSV
      test_run_no: '2982'
      time: '16:52:42'
      user: USER
  plate_9:
    control:
      date: 22/04/2022
      id1: null
      id2: null
      machine: BMG CLARIOstar
      path: ../../lab/01.0/../../lab/01.0/platereader/22042022,142723.CSV
      test_run_no: '2878'
      time: '14:27:23'
      user: USER
    test:
      date: 26/04/2022
      id1: null
      id2: 1yqo
      machine: BMG CLARIOstar
      path: ../../lab/04.0/platereader/TRno2983.CSV
      test_run_no: '2983'
      time: '17:02:17'
      user: USER
uv-vis:
  post-dilution spec: []
  pre-dilution spec:
  - ../../lab/04.0/uv-vis/20220426-exp04-1yqp-predil.csv

